version: '3'

services:
  # Сервис для приложения Spring Boot
  spring-app:
    image: aasurov/anvilcoder:checkpoint-manager-${PROJECT_VERSION}
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
      - avatars-storage
    volumes:
      - logs:/path/to/remote/logs # Использование именованного тома для логов
    environment:
      - LOGGING_CONFIG=classpath:logback-prod-docker.xml
      - LOG_PATH=/path/to/remote/logs
      - DB_URL=jdbc:postgresql://postgres-db:5432/chpmanDB
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/chpmanDB
      - SPRING_DATASOURCE_USERNAME=chpman
      - SPRING_DATASOURCE_PASSWORD=chpmanPass%
      - AVATAR_STORAGE_PATH=/avatars
      - TZ=UTC
      - JASYPT_ENCRYPTOR_PASSWORD=${JASYPT_ENCRYPTOR_PASSWORD}

  # Сервис для базы данных PostgreSQL
  postgres-db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=chpmanDB
      - POSTGRES_USER=chpman
      - POSTGRES_PASSWORD=chpmanPass%
      - TZ=UTC

  # Сервис для хранения аватаров
  avatars-storage:
    image: nginx:latest
    volumes:
      - avatars:/usr/share/nginx/html:ro # Использование именованного тома для аватаров
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # Монтирование конфигурационного файла nginx
      - logs:/var/log/nginx # Путь к логам nginx внутри контейнера
    ports:
      - "8081:80"
    environment:
      - TZ=UTC

volumes:
  avatars: # Определение именованного тома для аватаров
  logs: # Определение именованного тома для логов
