version: '3'

services:
  # Сервис для приложения Spring Boot
  spring-app:
    image: aasurov/anvilcoder:checkpoint-manager-${PROJECT_VERSION}
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
      - avatars-storage
      - redis-cache
    volumes:
      - logs:/path/to/remote/logs # Использование именованного тома для логов
    environment:
      - LOGGING_CONFIG=classpath:logback-prod-docker.xml
      - LOG_PATH=/path/to/remote/logs
      - DB_URL=jdbc:postgresql://postgres-db:5432/chpmanDB
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/chpmanDB
      - SPRING_DATASOURCE_USERNAME=chpman
      - SPRING_DATASOURCE_PASSWORD=chpmanPass%
      - SPRING_DATA_REDIS_HOST=redis-cache
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_DATA_REDIS_PASSWORD=admin
      - AVATAR_STORAGE_PATH=/avatars
      - TZ=UTC
      - JASYPT_ENCRYPTOR_PASSWORD=${JASYPT_ENCRYPTOR_PASSWORD}

  # Сервис для базы данных PostgreSQL
  postgres-db:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=chpmanDB
      - POSTGRES_USER=chpman
      - POSTGRES_PASSWORD=chpmanPass%
      - TZ=UTC

  #Сервис для кеширования в Redis
  redis-cache:
    container_name: redis-cache
    hostname: redis-cache
    image: redis:latest
    ports:
      - "6379:6379"
    restart: on-failure
    volumes:
      - ./config/redis/redis.conf:/usr/local/etc/redis/redis.conf #copy config to redis
      - redis-cache-data:/data
    command: redis-server /usr/local/etc/redis/redis.conf #start with our config


  # Сервис для хранения аватаров
  avatars-storage:
    image: nginx:latest
    volumes:
      - avatars:/usr/share/nginx/html:ro # Использование именованного тома для аватаров
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # Монтирование конфигурационного файла nginx
      - logs:/var/log/nginx # Путь к логам nginx внутри контейнера
    ports:
      - "8081:80"
    environment:
      - TZ=UTC


volumes:
  avatars: # Определение именованного тома для аватаров
  logs: # Определение именованного тома для логов
  db-data: # Определение именованного тома для базы данных
  redis-cache-data: # Вольюм для редиса, откуда он сюда подставится?
