version: '3'

services:
  # Сервис для приложения Spring Boot
  spring-app:
    image: checkpoint-manager:${PROJECT_VERSION}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      avatars-storage:
        condition: service_started
      redis-cache:
        condition: service_started
      postgres-db:
        condition: service_healthy
    volumes:
      - ./logs:/logs # Монтирование локальной директории для логов
    environment:
      - LOGGING_CONFIG=classpath:logback-local-docker.xml # Для запуска с Docker
      - LOG_PATH=/logs
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/${PG_DB}
      - SPRING_DATASOURCE_USERNAME=${PG_USER}
      - SPRING_DATASOURCE_PASSWORD=${PG_PASS}
      - SPRING_DATA_REDIS_HOST=redis-cache
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_DATA_REDIS_PASSWORD=${REDIS_PASS}
      - AVATAR_STORAGE_PATH=/avatars
      - TZ=UTC
    env_file:
      - .env
  # Сервис для базы данных PostgreSQL
  postgres-db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${PG_DB}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
      - TZ=UTC
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 10s
      retries: 5
  #Сервис для кеширования в Redis
  redis-cache:
    container_name: redis-cache
    hostname: redis-cache
    image: redis:latest
    ports:
      - "6379:6379"
    restart: on-failure
    volumes:
      - ./config/redis/redis.conf:/usr/local/etc/redis/redis.conf #copy config to redis
      - redis-cache-data:/data
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass ${REDIS_PASS}
    depends_on:
      - postgres-db

  # Сервис для хранения аватаров
  avatars-storage:
    image: nginx:latest
    volumes:
      - ./avatars:/usr/share/nginx/html:ro
    ports:
      - "8081:80"
    environment:
      - TZ=UTC

volumes:
  redis-cache-data: