output.logstash:
  # The Logstash hosts
  hosts: [ "logstash:5044" ]
  enabled: true

filebeat.inputs:
  - type: log
    paths:
      - /var/log/filebeat/logs/*.log #from here filebeat will read logs
    enabled: true