spring:
  mail:
    host: smtp.yandex.ru
    port: 465
    username: ENC(03puLAyfAIk49/ksIDYBr9mUvKGeiFOxvKlNPiYbjuzhhxsJKAZjM0RxysGTxpsGy4n2HZVr0msCkOIl/5ejkA==)
    password: ENC(IoIoNKoDTPRhpM4jD7zvwNBjUBMgfrynz7Ar+bTsf3/ea6PCMAF1bq+3w37p1fA2j/waqrSWgYzvAphHaT08bQ==)
    protocol: smtp
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          auth: true
          starttls:
            enable: true
  data:
    redis:
      host: redis-cache
      port: 6379
      jedis:
        pool:
        # Здесь указать параметры пула соединений, если необходимо
      password: admin

app:
  confirmation-link: https://checkpoint-manager.vercel.app/registration/
  confirmation-email-link: https://checkpoint-manager.ru/api/v1/confirm/email?token=

cors:
  allowed-origins:
    - "http://localhost:3000" #React локал (удалить потом)
    - "http://192.168.1.37:3000" #Сонин Ip (удалить потом)
    - "http://192.168.31.74:3000" #Сони Ip (удалить потом)
    - "http://192.168.1.55:3000" #Жени Ip(удалить потом)
    - "https://checkpoint-manager.vercel.app" #Приложение для фронта(для тестирования).
    - "https://checkpoint-manager.ru"
    - "https://www.checkpoint-manager.ru"
    - "https://55ef-95-82-241-230.ngrok-free.app" #Наставник Сони
    - "http://84.252.74.180:8080" #если отваливается checkpoint
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - PATCH

  allowed-headers:
    - "Authorization"
    - "Content-Type"

  allow-credentials: true

logging:
  config: classpath:logback-prod.xml
  aspect:
    call-service: true

springdoc:
  pre-loading-enabled: false
  cache:
    disabled: false