app:
  version: ${version}
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/chpmanDB
    username: chpman
    password: chpmanPass%
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
    hibernate:
      ddl-auto: validate
  flyway:
    sqlMigrationPrefix: V
    locations: classpath:migration
    enabled: true
#  liquibase:
#    change-log: classpath:qp/migration
#    contexts: default
#    default-schema: public
#    drop-first: false
#    enabled: true
