app:
  version: ${PROJECT_VERSION}
  confirmation-link: http://localhost:8080/api/v1/confirm/registration?token=
  confirmation-email-link: http://localhost:8080/api/v1/confirm/email?token=
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/${PG_DB}
    username: ENC(lsksaRYX3S2BuNlhosZLveISYQEf7AqUSFEE1kYGPo4lWAkFx47mAs6Nn9KB0H1e)
    password: ENC(/xwd4WaJRFnFP+HJu3gBu6XkgycEKqOOGQd9eBWMdpBsOfagzSjskd+SDZjknZeJ)
  servlet:
    multipart:
      max-file-size: 5MB
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        ddl-auto: validate
        use_sql_comments: true
      jdbc:
        time-zone: UTC
  jackson:
    time-zone: UTC
  liquibase:
    change-log: classpath:liquibase/changelog-master.yml
    contexts: default
    default-schema: public
    drop-first: false
    enabled: true
  profiles:
    active: dev
  mail:
    host: smtp.yandex.ru
    port: 465
    username: ENC(ddovr6Xerz5RXQS3vmc3DtSXnYW7/k8akDrcmMbw3ehZKth1dkNQ5bYKuUcq/nqLtAP9+2JB+anKvF40No5YPQ==)
    password: ENC(Mmts7jvfpwm1xysyblPFxswQ2PmspS4iSx2zFT9YUg/kkDkX2inLeL3LF1R3h+MCLowaVXjoYblacqcy6+aSdQ==)
    protocol: smtp
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          auth: true
          starttls:
            enable: true
  data:
    redis:
      host: localhost
      port: 6379
      jedis:
        pool:
          enabled: true
          max-active: 10
          max-idle: 5
          max-wait: -1ms
          min-idle: 1
      password: admin

application:
  security:
    jwt:
      secret-key: ENC(QSwxn0NCNAFzcJprJPe6hlv+kH37gZDbUOsVl9tcF2RtfiRmcDEKYWkril6ZvFlVDnSjQzrg2gHuzK79fof3UhvrBkEtC+dBQ9r/vlI2sl62AJ8CiRmzuNMdb/WDj1mz+RWRUlaezVJRZjitEFfWpw==)
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

cors:
  allowed-origins:
    - "*"
  allowed-methods:
    - "*"
  allowed-headers:
    - "*"

  allow-credentials: true

avatars:
  dir:
  extensions: jpg, jpeg, png, ico, gif, eps, svg, bmp
  max-size: 5MB # Максимальный размер файла
  max-width: 400 # максимальная ширина изображения
  max-height: 400 # максимальная высота изображения
  content-type: "image/"

logging:
  config: classpath:logback-local.xml
