app:
  version: ${version}
  confirmation-link: http://localhost:8080/chpman/confirm/registration?token=
  confirmation-email-link: http://localhost:8080/chpman/confirm/email?token=
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/chpmanDB
    username: ENC(5HqytD0eVVx8qGMGQu8sTQ==)
    password: ENC(9SwZkb8QRqZYzm1kOZ0VKvYgHiRKmOCR)
  servlet:
    multipart:
      max-file-size: 5MB
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        ddl-auto: validate
        use_sql_comments: true
      jdbc:
        time-zone: UTC
  jackson:
    time-zone: UTC
  liquibase:
    change-log: classpath:liquibase/changelog-master.yml
    contexts: default
    default-schema: public
    drop-first: false
    enabled: true
  profiles:
    active: dev
  mail:
    host: smtp.yandex.ru
    port: 465
    username: ENC(dVpBOhqGH3wL3SOmDl2H7k7OF94q4NNWmtIA7owtFIE=)
    password: ENC(UyrF6XfE/xEJShixxamBcoBJG+DAVKy15WxgFj00KPM=)
    protocol: smtp
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          auth: true
          starttls:
            enable: true
application:
  security:
    jwt:
      secret-key: ENC(LgSa02Um+3umQ8fEpn2ftbUjAfbQ5gy9yLzM+C4H/BcjTpq3pQ/+LroJjjPOhM/dYYF6R7zFMnAsO71uUta3MXDCnKlSGg5VU9sfc5X939A=)
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
avatars:
  dir:
    path: ./avatars
  extensions: jpg, jpeg, png, ico, gif, eps, svg, bmp
  max-size: 5MB # Максимальный размер файла
  image:
    max-width: 400 # максимальная ширина изображения
    max-height: 400 # максимальная высота изображения
logging:
  config: classpath:logback-local.xml