spring:
  mail:
    host: smtp.yandex.ru
    port: 465
    username: ENC(t1KNUI2vMTTgyc1kx5sbIzBgkqsC193CqyI/BTecn8+hAu54PXmidABUqaJXJJzw37CR/rcOqlzwc3wXgsY+cw==)
    password: ENC(8AQW3PxekAw2XOrN7wZECyY2R5jxy8LJS8aGwQ7l0c6JQYpeJ0rE8slUZoU4eGTmKwgOzR7iGGiPCSn7wMw1Cw==)
    protocol: smtp
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          auth: true
          starttls:
            enable: true
  data:
    redis:
      host: redis-cache
      port: 6379
      jedis:
        pool:
        # Здесь указать параметры пула соединений, если необходимо
      password: admin

app:
  confirmation-link: https://checkpoint-manager.vercel.app/registration/
  confirmation-email-link: https://checkpoint-manager.ru/api/v1/confirm/email?token=

cors:
  allowed-origins:
    - "http://localhost:3000" #React локал (удалить потом)
    - "http://192.168.1.37:3000" #Сонин Ip (удалить потом)
    - "http://192.168.31.74:3000" #Сони Ip (удалить потом)
    - "http://192.168.1.55:3000" #Жени Ip(удалить потом)
    - "https://checkpoint-manager.vercel.app" #Приложение для фронта(для тестирования).
    - "https://checkpoint-manager.ru"
    - "https://www.checkpoint-manager.ru"
    - "https://55ef-95-82-241-230.ngrok-free.app" #Наставник Сони
    - "http://84.252.74.180:8080" #если отваливается checkpoint
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - PATCH

  allowed-headers:
    - "Authorization"
    - "Content-Type"

  allow-credentials: true

logging:
  config: classpath:logback-prod.xml
  aspect:
    call-service: true
    include-private: false

springdoc:
  pre-loading-enabled: false
  cache:
    disabled: false

donation:
  return-url: "https://checkpoint-manager.ru"

yookassa:
  secret-key: ENC(w69fQPDF+ytHWq5KlQq5I/u1ndZaHnfx0YkKyx6QhPizrkfgoy7rjRk+nLp0tpOjdek37q2XCAE20E+X2dsud9IBTJmvQwJwVSRCvW8teOxYVrPvp33V5Vx1BbUFmQPB)
  shop-id: ENC(S3WNIfDRyOlU7uCuhVrOG9qXMXRR/Z/Y87wUiCK8eZjR8PJfQtOKyfFAt6cjBK4m)
  url: "https://api.yookassa.ru/v3"
