spring:
  mail:
    host: smtp.yandex.ru
    port: 465
    username: ENC(W2WL3BQ970dUP//5UzsvNBQvNKaYgz2Mr5HkvijE16lLtUKcSykRYtuq3PDnrvLSxj1vVZNA6Xv4XMzDUFb14A==)
    password: ENC(/5wosjHaClDmWehH02RXSaT2/yTz0Ox1ZyEAQB3pQXs9k2jtn/yrtBOZgoT9MH6dRWNeiuSCPu6ds42vJkPAzg==)
    protocol: smtp
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          auth: true
          starttls:
            enable: true
app:
  confirmation-link: https://checkpoint-manager.ru/api/v1/confirm/registration?token=
  confirmation-email-link: https://checkpoint-manager.ru/api/v1/confirm/email?token=
logging:
  config: classpath:logback-prod.xml