app:
  version: ${PROJECT_VERSION}
  confirmation-link: http://localhost:8080/api/v1/confirm/registration?token=
  confirmation-email-link: http://localhost:8080/api/v1/confirm/email?token=
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/${PG_DB}
    username: ENC(9k2UuAIGxxGILVSL+5HgpsnQkEPp2tkJf6jzDEh3bWR5l504rjbqZVYs72snlbFj)
    password: ENC(6udLr6OyhcjLhsBgtcMIxwv4vsDvQZqiUMvpVir8iY4nj9M4nMmItjElLeAZFvFK)
  servlet:
    multipart:
      max-file-size: 5MB
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        ddl-auto: validate
        use_sql_comments: true
      jdbc:
        time-zone: UTC
  jackson:
    time-zone: UTC
  liquibase:
    change-log: classpath:liquibase/changelog-master.yml
    contexts: default
    default-schema: public
    drop-first: false
    enabled: true
  profiles:
    active: dev
  mail:
    host: smtp.yandex.ru
    port: 465
    username: ENC(2CNcQ+pxJrvy/gJ2OqPmPBCLETyaw96OApJ9ZoDwmshV0phAWM2+cZy+L8eU9lAjAi0eYRlZ8f7h3KKGs8Q35w==)
    password: ENC(3ZZqKWtLB3XcA4FZ6cfzinSHOkzS2PC8QzMljRtk37kWg8zEgizYTpN3C8jrmTS9)
    protocol: smtp
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          auth: true
          starttls:
            enable: true
  data:
    redis:
      host: localhost
      port: 6379
      jedis:
        pool:
          enabled: true
          max-active: 10
          max-idle: 5
          max-wait: -1ms
          min-idle: 1
      password: admin

application:
  security:
    jwt:
      secret-key: ENC(IFQIDSQX+poqlHFPutCvUd7m8Wn3obL8WKAwIC5fnxjGUnev47jsZ4q5MpPdvuUwpiHY+30ODWcsuSE0aVG1TQ3AZTLPBlETCSmhXzmw3uj+aWMn29T0Vz1c6THVVFDyO0iaXJA5J12NRUZMdHZVoQ==)
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

cors:
  allowed-origins:
    - "*"
  allowed-methods:
    - "*"
  allowed-headers:
    - "*"

  allow-credentials: true

avatars:
  dir:
  extensions: jpg, jpeg, png, ico, gif, eps, svg, bmp
  max-size: 5MB # Максимальный размер файла
  max-width: 400 # максимальная ширина изображения
  max-height: 400 # максимальная высота изображения
  content-type: "image/"

logging:
  config: classpath:logback-local.xml
