FROM postgres:latest

# Дока на плагин
# https://github.com/citusdata/pg_cron

RUN apt update && apt install -y postgresql-16-cron

COPY ./init-db.sh /docker-entrypoint-initdb.d/
COPY ./.pgpass /root/

RUN chmod 600 /root/.pgpass