-- liquibase formatted sql

-- changeset x3imal:174

ALTER TABLE cars
    ALTER COLUMN brand_id TYPE BIGINT;

ALTER TABLE car_brand
    ALTER COLUMN id TYPE BIGINT;

ALTER TABLE cars
    ALTER COLUMN brand_id DROP DEFAULT;

ALTER TABLE car_brand
    ALTER COLUMN id DROP DEFAULT;

DROP SEQUENCE IF EXISTS cars_brand_id_seq;

DROP SEQUENCE IF EXISTS car_brand_id_seq;


ALTER TABLE car_brand
    ALTER COLUMN id DROP DEFAULT;

ALTER TABLE car_brand
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;


